"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const translations = {
    en: {
        'nav.home': 'Home',
        'nav.artists': 'Artists',
        'nav.news': 'News',
        'nav.login': 'Login',
        'nav.signup': 'Sign Up',
        'settings.title': 'Settings',
        'settings.language': 'Language',
        'settings.language.desc': 'Select your preferred language for the interface.',
        'user.profile': 'Profile',
        'user.settings': 'Settings',
        'user.logout': 'Logout',
        'news.title': 'Music News',
        'news.subtitle': 'Stay updated with the latest stories, reviews, and industry insights from the music world.',
        'news.loading': 'Loading news...',
        'news.empty': 'No news found in this category.',
        'artists.title': 'Discover Artists',
        'artists.subtitle': 'Find your new favorite sound from our curated collection. Filter by genre or popularity.',
        'artists.search': 'Search artists...',
        'artists.top_only': 'Top Artists Only',
        'artists.show_top': 'Show Top Artists',
        'artists.loading': 'Loading artists...',
        'artists.empty': 'No artists found',
        'artists.empty_desc': 'Try adjusting your search or filters',
        'genre.Pop': 'Pop',
        'genre.Rock': 'Rock',
        'genre.Indie': 'Indie',
        'genre.Hip Hop': 'Hip Hop',
        'genre.Rap': 'Rap',
        'genre.Electronic': 'Electronic',
        'genre.Jazz': 'Jazz',
        'genre.Classical': 'Classical',
        'genre.Metal': 'Metal',
        'genre.Country': 'Country',
        'genre.R&B': 'R&B',
        'category.Industry': 'Industry',
        'category.Reviews': 'Reviews',
        'category.Releases': 'Releases',
        'category.Live': 'Live',
        'contact.title': 'Contact Us',
        'contact.subtitle': 'Have questions or suggestions? We\'d love to hear from you.',
        'contact.form.name': 'Name',
        'contact.form.name_placeholder': 'Your name',
        'contact.form.email': 'Email',
        'contact.form.email_placeholder': 'your@email.com',
        'contact.form.message': 'Message',
        'contact.form.message_placeholder': 'How can we help you?',
        'contact.form.send': 'Send Message',
        'contact.form.sending': 'Sending...',
        'contact.form.success': 'Message sent successfully!',
        'contact.form.error': 'Error sending message. Please try again.',
        'contact.social.title': 'Social Media',
        'artist.about': 'About',
        'artist.popular_songs': 'Popular Songs',
        'artist.discography': 'Discography',
        'artist.listeners': 'Monthly Listeners',
        'artist.top_songs': 'Top Songs',
        'artist.albums': 'Albums',
        'artist.total_plays': 'Total Plays',
        'artist.plays': 'plays',
        'artist.not_found': 'Artist not found',
        'home.hero.title': 'Discover Your Next Favorite Artist',
        'home.hero.subtitle': 'Explore a world of music, from chart-topping hits to underground gems.',
        'home.hero.cta': 'Start Listening',
        'home.featured.title': 'Featured Artists',
        'home.featured.subtitle': 'Hand-picked artists making waves right now.',
        'home.news.title': 'Latest News',
        'home.news.subtitle': 'What\'s happening in the music world.',
        'home.contact.title': 'Get in Touch',
        'home.contact.subtitle': 'We\'d love to hear from you.',
        'home.contact.cta': 'Contact Us',
        'home.popularSongs.title': 'Popular Songs',
        'artist.stats': 'Artist Stats',
        'artist.now_playing': 'Now Playing',
        'news.comments.title': 'Comments',
        'news.comments.placeholder': 'Leave a comment...',
        'news.comments.post': 'Post Comment',
        'news.comments.posting': 'Posting...',
        'news.comments.login_prompt': 'Please login to leave a comment.',
        'news.comments.empty': 'No comments yet. Be the first to comment!',
        'news.views': 'views',
        'settings.avatar.change': 'Change Avatar',
        'settings.avatar.uploading': 'Uploading...',
        'settings.avatar.success': 'Avatar uploaded successfully!',
        'settings.form.username': 'Username',
        'settings.form.email': 'Email',
        'settings.form.new_password': 'New Password',
        'settings.form.confirm_password': 'Confirm Password',
        'settings.form.save': 'Save Changes',
        'settings.form.saving': 'Saving...',
        'settings.profile.success': 'Profile updated successfully!',
        'settings.error.password_mismatch': 'Passwords do not match',
        'settings.error.password_length': 'Password must be at least 6 characters',
        'settings.security': 'Security',
        'settings.change_password': 'Change Password',
        'settings.form.current_password': 'Current Password',
        'settings.form.update_password': 'Update Password',
        'settings.error.current_password_incorrect': 'Incorrect current password',
        'settings.error.file_size': 'File size must be less than 5MB',
        'settings.password.success': 'Password updated successfully!',
        'settings.edit': 'Edit',
        'settings.cancel': 'Cancel',
        'settings.security.last_changed': 'Last Password Change',
        'settings.security.level': 'Security Level',
        'settings.security.weak': 'Weak',
        'settings.security.medium': 'Medium',
        'settings.security.strong': 'Strong',
        'settings.security.never': 'Never',
        'settings.personal_info': 'Personal Information',
        'user.anonymous': 'Anonymous',
        'auth.login.title': 'Sign in to your account',
        'auth.login.subtitle': "Don't have an account?",
        'auth.login.cta': 'Sign up',
        'auth.login.button': 'Sign in',
        'auth.login.signing_in': 'Signing in...',
        'auth.signup.title': 'Create your account',
        'auth.signup.subtitle': 'Already have an account?',
        'auth.signup.cta': 'Sign in',
        'auth.signup.button': 'Create Account',
        'auth.signup.creating': 'Creating account...',
        'auth.form.email': 'Email address',
        'auth.form.password': 'Password',
        'auth.form.username': 'Username',
        'auth.form.confirm_password': 'Confirm Password',
        'auth.error.password_match': 'Passwords do not match',
        'auth.error.password_length': 'Password must be at least 6 characters',
        'auth.error.password_symbol': 'Password must contain at least one symbol',
        'auth.error.username_required': 'Username is required',
        'auth.error.username_length': 'Username must be at least 3 characters',
        'auth.error.email_required': 'Email is required',
        'auth.error.email_invalid': 'Please enter a valid email address',
        'home.hero.badge': 'Discover New Music',
        'home.stats.artists': 'Artists',
        'home.stats.news': 'News Articles',
        'home.stats.updates': 'Updates',
        'home.scroll': 'Scroll to explore',
        'home.features.title': 'Why Choose MusicDisc?',
        'home.features.discover.title': 'Discover',
        'home.features.discover.desc': 'Explore thousands of artists from every genre',
        'home.features.news.title': 'Stay Updated',
        'home.features.news.desc': 'Latest music news and releases daily',
        'home.features.listen.title': 'Listen',
        'home.features.listen.desc': 'Preview tracks directly from Spotify',
        'home.features.save.title': 'Save Favorites',
        'home.features.save.desc': 'Create your personal music collection',
        'footer.description': 'Discover new artists, explore music news, and stay connected with the global music community.',
        'footer.platform': 'Platform',
        'footer.resources': 'Resources',
        'footer.legal': 'Legal',
        'footer.about': 'About',
        'footer.contact': 'Contact',
        'footer.faq': 'FAQ',
        'footer.help': 'Help Center',
        'footer.api': 'API',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.cookies': 'Cookie Policy',
        'footer.rights': 'All rights reserved.',
        'footer.secure': 'Secure',
        'footer.trusted': 'Trusted',
        'terms.title': 'Terms of Service',
        'terms.last_updated': 'Last Updated: November 28, 2025',
        'terms.intro': 'Welcome to MusicDisc. By accessing our website, you agree to be bound by these Terms of Service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.',
        'terms.acceptance': '1. Acceptance of Terms',
        'terms.acceptance.desc': 'By accessing or using our service, you agree to be bound by these terms. If you disagree with any part of the terms, then you may not access the service.',
        'terms.accounts': '2. User Accounts',
        'terms.accounts.desc': 'When you create an account with us, you must provide us information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service.',
        'terms.content': '3. Content',
        'terms.content.desc': 'Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material. You are responsible for the content that you post to the Service, including its legality, reliability, and appropriateness.',
        'terms.intellectual_property': '4. Intellectual Property',
        'terms.intellectual_property.desc': 'The Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of MusicDisc and its licensors.',
        'terms.termination': '5. Termination',
        'terms.termination.desc': 'We may terminate or suspend access to our Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.',
        'terms.limitation': '6. Limitation of Liability',
        'terms.limitation.desc': 'In no event shall MusicDisc, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.',
        'terms.changes': '7. Changes',
        'terms.changes.desc': 'We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect.',
        'terms.contact': '8. Contact Us',
        'terms.contact.desc': 'If you have any questions about these Terms, please contact us at flowmusichub@gmail.com.',
        'privacy.title': 'Privacy Policy',
        'privacy.last_updated': 'Last Updated: November 28, 2025',
        'privacy.intro': 'At MusicDisc, accessible from musicdisc.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by MusicDisc and how we use it.',
        'privacy.collection': '1. Information We Collect',
        'privacy.collection.desc': 'We collect several different types of information for various purposes to provide and improve our Service to you, including Personal Data (email, name) and Usage Data.',
        'privacy.use': '2. How We Use Your Information',
        'privacy.use.desc': 'We use the collected data for various purposes: to provide and maintain our Service, to notify you about changes to our Service, to allow you to participate in interactive features of our Service when you choose to do so, to provide customer support, and to gather analysis or valuable information so that we can improve our Service.',
        'privacy.sharing': '3. Sharing Your Information',
        'privacy.sharing.desc': 'We do not sell, trade, or otherwise transfer to outside parties your Personally Identifiable Information unless we provide users with advance notice. This does not include website hosting partners and other parties who assist us in operating our website, conducting our business, or serving our users.',
        'privacy.security': '4. Data Security',
        'privacy.security.desc': 'The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.',
        'privacy.cookies': '5. Cookies',
        'privacy.cookies.desc': 'We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.',
        'privacy.rights': '6. Your Data Protection Rights',
        'privacy.rights.desc': 'We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following: The right to access, rectification, erasure, restrict processing, object to processing, and data portability.',
        'privacy.contact': '7. Contact Us',
        'privacy.contact.desc': 'If you have any questions about this Privacy Policy, please contact us at flowmusichub@gmail.com.',
    },
    es: {
        'nav.home': 'Inicio',
        'nav.artists': 'Artistas',
        'nav.news': 'Noticias',
        'nav.login': 'Iniciar Sesión',
        'nav.signup': 'Registrarse',
        'settings.title': 'Ajustes',
        'settings.language': 'Idioma',
        'settings.language.desc': 'Selecciona tu idioma preferido para la interfaz.',
        'user.profile': 'Perfil',
        'user.settings': 'Ajustes',
        'user.logout': 'Cerrar Sesión',
        'news.title': 'Noticias Musicales',
        'news.subtitle': 'Mantente actualizado con las últimas historias, reseñas y noticias de la industria musical.',
        'news.loading': 'Cargando noticias...',
        'news.empty': 'No se encontraron noticias en esta categoría.',
        'artists.title': 'Descubrir Artistas',
        'artists.subtitle': 'Encuentra tu nuevo sonido favorito en nuestra colección curada. Filtra por género o popularidad.',
        'artists.search': 'Buscar artistas...',
        'artists.top_only': 'Solo Top Artistas',
        'artists.show_top': 'Mostrar Top Artistas',
        'artists.loading': 'Cargando artistas...',
        'artists.empty': 'No se encontraron artistas',
        'artists.empty_desc': 'Intenta ajustar tu búsqueda o filtros',
        'genre.Pop': 'Pop',
        'genre.Rock': 'Rock',
        'genre.Indie': 'Indie',
        'genre.Hip Hop': 'Hip Hop',
        'genre.Rap': 'Rap',
        'genre.Electronic': 'Electrónica',
        'genre.Jazz': 'Jazz',
        'genre.Classical': 'Clásica',
        'genre.Metal': 'Metal',
        'genre.Country': 'Country',
        'genre.R&B': 'R&B',
        'category.Industry': 'Industria',
        'category.Reviews': 'Reseñas',
        'category.Releases': 'Lanzamientos',
        'category.Live': 'En Vivo',
        'contact.title': 'Contáctanos',
        'contact.subtitle': '¿Tienes preguntas o sugerencias? Nos encantaría escucharte.',
        'contact.form.name': 'Nombre de usuario',
        'contact.form.name_placeholder': 'Tu nombre',
        'contact.form.email': 'Correo Electrónico',
        'contact.form.email_placeholder': 'tu@correo.com',
        'contact.form.message': 'Mensaje',
        'contact.form.message_placeholder': 'Escribe tu mensaje',
        'contact.form.send': 'Enviar Mensaje',
        'contact.form.sending': 'Enviando...',
        'contact.form.success': '¡Mensaje enviado con éxito!',
        'contact.form.error': 'Error al enviar el mensaje. Inténtalo de nuevo.',
        'contact.social.title': 'Redes Sociales',
        'artist.about': 'Acerca de',
        'artist.popular_songs': 'Canciones Populares',
        'artist.discography': 'Discografía',
        'artist.listeners': 'Oyentes Mensuales',
        'artist.top_songs': 'Top Canciones',
        'artist.albums': 'Álbumes',
        'artist.total_plays': 'Reproducciones Totales',
        'artist.plays': 'reproducciones',
        'artist.not_found': 'Artista no encontrado',
        'home.hero.title': 'Descubre tu Próximo Artista Favorito',
        'home.hero.subtitle': 'Explora un mundo de música, desde éxitos de las listas hasta joyas underground.',
        'home.hero.cta': 'Empezar a Escuchar',
        'home.featured.title': 'Artistas Destacados',
        'home.featured.subtitle': 'Artistas seleccionados que están marcando tendencia ahora mismo.',
        'home.news.title': 'Últimas Noticias',
        'home.news.subtitle': 'Lo que está pasando en el mundo de la música.',
        'home.contact.title': 'Ponte en Contacto',
        'home.contact.subtitle': 'Nos encantaría saber de ti.',
        'home.contact.cta': 'Contáctanos',
        'home.popularSongs.title': 'Canciones Populares',
        'artist.stats': 'Estadísticas del Artista',
        'artist.now_playing': 'Reproduciendo Ahora',
        'news.comments.title': 'Comentarios',
        'news.comments.placeholder': 'Deja un comentario...',
        'news.comments.post': 'Publicar Comentario',
        'news.comments.posting': 'Publicando...',
        'news.comments.login_prompt': 'Por favor inicia sesión para dejar un comentario.',
        'news.comments.empty': 'Aún no hay comentarios. ¡Sé el primero en comentar!',
        'news.views': 'vistas',
        'settings.avatar.change': 'Cambiar Avatar',
        'settings.avatar.uploading': 'Subiendo...',
        'settings.avatar.success': '¡Avatar subido con éxito!',
        'settings.form.username': 'Nombre de usuario',
        'settings.form.email': 'Correo electrónico',
        'settings.form.new_password': 'Nueva Contraseña',
        'settings.form.confirm_password': 'Confirmar Contraseña',
        'settings.form.save': 'Guardar Cambios',
        'settings.form.saving': 'Guardando...',
        'settings.profile.success': '¡Perfil actualizado con éxito!',
        'settings.error.password_mismatch': 'Las contraseñas no coinciden',
        'settings.error.password_length': 'La contraseña debe tener al menos 6 caracteres',
        'settings.security': 'Seguridad',
        'settings.change_password': 'Cambiar Contraseña',
        'settings.form.current_password': 'Contraseña Actual',
        'settings.form.update_password': 'Actualizar Contraseña',
        'settings.error.current_password_incorrect': 'La contraseña actual es incorrecta',
        'settings.error.file_size': 'El archivo debe pesar menos de 5MB',
        'settings.password.success': '¡Contraseña actualizada con éxito!',
        'settings.edit': 'Editar',
        'settings.cancel': 'Cancelar',
        'settings.security.last_changed': 'Último cambio de contraseña',
        'settings.security.level': 'Nivel de seguridad',
        'settings.security.weak': 'Débil',
        'settings.security.medium': 'Medio',
        'settings.security.strong': 'Fuerte',
        'settings.security.never': 'Nunca',
        'settings.personal_info': 'Información Personal',
        'user.anonymous': 'Anónimo',
        'auth.login.title': 'Inicia sesión en tu cuenta',
        'auth.login.subtitle': '¿No tienes una cuenta?',
        'auth.login.cta': 'Regístrate',
        'auth.login.button': 'Iniciar sesión',
        'auth.login.signing_in': 'Iniciando sesión...',
        'auth.signup.title': 'Crea tu cuenta',
        'auth.signup.subtitle': '¿Ya tienes una cuenta?',
        'auth.signup.cta': 'Inicia sesión',
        'auth.signup.button': 'Crear Cuenta',
        'auth.signup.creating': 'Creando cuenta...',
        'auth.form.email': 'Correo electrónico',
        'auth.form.password': 'Contraseña',
        'auth.form.username': 'Nombre de usuario',
        'auth.form.confirm_password': 'Confirmar Contraseña',
        'auth.error.password_match': 'Las contraseñas no coinciden',
        'auth.error.password_length': 'La contraseña debe tener al menos 6 caracteres',
        'auth.error.password_symbol': 'La contraseña debe contener al menos un símbolo',
        'auth.error.username_required': 'El nombre de usuario es obligatorio',
        'auth.error.username_length': 'El nombre de usuario debe tener al menos 3 caracteres',
        'auth.error.email_required': 'El correo electrónico es obligatorio',
        'auth.error.email_invalid': 'Por favor introduce un correo válido',
        'home.hero.badge': 'Descubre Nueva Música',
        'home.stats.artists': 'Artistas',
        'home.stats.news': 'Artículos',
        'home.stats.updates': 'Actualizaciones',
        'home.scroll': 'Desplázate para explorar',
        'home.features.title': '¿Por qué elegir MusicDisc?',
        'home.features.discover.title': 'Descubre',
        'home.features.discover.desc': 'Explora miles de artistas de todos los géneros',
        'home.features.news.title': 'Mantente Actualizado',
        'home.features.news.desc': 'Últimas noticias musicales y lanzamientos diarios',
        'home.features.listen.title': 'Escucha',
        'home.features.listen.desc': 'Previsualiza canciones directamente desde Spotify',
        'home.features.save.title': 'Guarda Favoritos',
        'home.features.save.desc': 'Crea tu colección personal de música',
        'footer.description': 'Descubre nuevos artistas, explora noticias musicales y mantente conectado con la comunidad musical global.',
        'footer.platform': 'Plataforma',
        'footer.resources': 'Recursos',
        'footer.legal': 'Legal',
        'footer.about': 'Acerca de',
        'footer.contact': 'Contacto',
        'footer.faq': 'Preguntas Frecuentes',
        'footer.help': 'Centro de Ayuda',
        'footer.api': 'API',
        'footer.privacy': 'Política de Privacidad',
        'footer.terms': 'Términos de Servicio',
        'footer.cookies': 'Política de Cookies',
        'footer.rights': 'Todos los derechos reservados.',
        'footer.secure': 'Seguro',
        'footer.trusted': 'Confiable',
        'terms.title': 'Términos de Servicio',
        'terms.last_updated': 'Última actualización: 28 de Noviembre, 2025',
        'terms.intro': 'Bienvenido a MusicDisc. Al acceder a nuestro sitio web, aceptas estar sujeto a estos Términos de Servicio, todas las leyes y regulaciones aplicables, y aceptas que eres responsable del cumplimiento de las leyes locales aplicables.',
        'terms.acceptance': '1. Aceptación de los Términos',
        'terms.acceptance.desc': 'Al acceder o utilizar nuestro servicio, aceptas estar sujeto a estos términos. Si no estás de acuerdo con alguna parte de los términos, no podrás acceder al servicio.',
        'terms.accounts': '2. Cuentas de Usuario',
        'terms.accounts.desc': 'Cuando creas una cuenta con nosotros, debes proporcionarnos información precisa, completa y actual en todo momento. El no hacerlo constituye una violación de los Términos, lo que puede resultar en la terminación inmediata de tu cuenta en nuestro Servicio.',
        'terms.content': '3. Contenido',
        'terms.content.desc': 'Nuestro Servicio te permite publicar, enlazar, almacenar, compartir y poner a disposición cierta información, texto, gráficos, videos u otro material. Eres responsable del contenido que publiques en el Servicio, incluyendo su legalidad, fiabilidad y adecuación.',
        'terms.intellectual_property': '4. Propiedad Intelectual',
        'terms.intellectual_property.desc': 'El Servicio y su contenido original (excluyendo el Contenido proporcionado por los usuarios), características y funcionalidad son y seguirán siendo propiedad exclusiva de MusicDisc y sus licenciantes.',
        'terms.termination': '5. Terminación',
        'terms.termination.desc': 'Podemos terminar o suspender el acceso a nuestro Servicio inmediatamente, sin previo aviso o responsabilidad, por cualquier motivo, incluyendo, sin limitación, si incumples los Términos.',
        'terms.limitation': '6. Limitación de Responsabilidad',
        'terms.limitation.desc': 'En ningún caso MusicDisc, ni sus directores, empleados, socios, agentes, proveedores o afiliados, serán responsables de ningún daño indirecto, incidental, especial, consecuente o punitivo, incluyendo, sin limitación, pérdida de beneficios, datos, uso, buena voluntad u otras pérdidas intangibles.',
        'terms.changes': '7. Cambios',
        'terms.changes.desc': 'Nos reservamos el derecho, a nuestra sola discreción, de modificar o reemplazar estos Términos en cualquier momento. Si una revisión es material, intentaremos proporcionar un aviso de al menos 30 días antes de que entren en vigor los nuevos términos.',
        'terms.contact': '8. Contáctanos',
        'terms.contact.desc': 'Si tienes alguna pregunta sobre estos Términos, por favor contáctanos en flowmusichub@gmail.com.',
        'privacy.title': 'Política de Privacidad',
        'privacy.last_updated': 'Última actualización: 28 de Noviembre, 2025',
        'privacy.intro': 'En MusicDisc, accesible desde musicdisc.com, una de nuestras principales prioridades es la privacidad de nuestros visitantes. Este documento de Política de Privacidad contiene tipos de información que es recopilada y registrada por MusicDisc y cómo la usamos.',
        'privacy.collection': '1. Información que Recopilamos',
        'privacy.collection.desc': 'Recopilamos varios tipos diferentes de información para diversos fines para proporcionar y mejorar nuestro Servicio para ti, incluyendo Datos Personales (correo electrónico, nombre) y Datos de Uso.',
        'privacy.use': '2. Cómo Usamos tu Información',
        'privacy.use.desc': 'Usamos los datos recopilados para diversos fines: para proporcionar y mantener nuestro Servicio, para notificarte sobre cambios en nuestro Servicio, para permitirte participar en funciones interactivas de nuestro Servicio cuando elijas hacerlo, para proporcionar atención al cliente y para recopilar análisis o información valiosa para que podamos mejorar nuestro Servicio.',
        'privacy.sharing': '3. Compartir tu Información',
        'privacy.sharing.desc': 'No vendemos, intercambiamos ni transferimos a terceros tu Información de Identificación Personal a menos que proporcionemos a los usuarios un aviso previo. Esto no incluye a los socios de alojamiento de sitios web y otras partes que nos ayudan a operar nuestro sitio web, llevar a cabo nuestro negocio o servir a nuestros usuarios.',
        'privacy.security': '4. Seguridad de los Datos',
        'privacy.security.desc': 'La seguridad de tus datos es importante para nosotros, pero recuerda que ningún método de transmisión a través de Internet o método de almacenamiento electrónico es 100% seguro. Si bien nos esforzamos por utilizar medios comercialmente aceptables para proteger tus Datos Personales, no podemos garantizar su seguridad absoluta.',
        'privacy.cookies': '5. Cookies',
        'privacy.cookies.desc': 'Utilizamos cookies y tecnologías de seguimiento similares para rastrear la actividad en nuestro Servicio y mantener cierta información. Puedes indicar a tu navegador que rechace todas las cookies o que indique cuándo se envía una cookie.',
        'privacy.rights': '6. Tus Derechos de Protección de Datos',
        'privacy.rights.desc': 'Nos gustaría asegurarnos de que eres plenamente consciente de todos tus derechos de protección de datos. Todo usuario tiene derecho a lo siguiente: El derecho a acceder, rectificación, borrado, restringir el procesamiento, oponerse al procesamiento y portabilidad de datos.',
        'privacy.contact': '7. Contáctanos',
        'privacy.contact.desc': 'Si tienes alguna pregunta sobre esta Política de Privacidad, por favor contáctanos en flowmusichub@gmail.com.',
    },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('es')

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language
        if (savedLang && Object.keys(translations).includes(savedLang)) {
            setLanguageState(savedLang)
        }
    }, [])

    const setLanguage = (lang: Language) => {
        setLanguageState(lang)
        localStorage.setItem('language', lang)
    }

    const t = (key: string): string => {
        const langData = translations[language] as Record<string, string>
        return langData[key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
