"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'es'

interface LanguageContextType {
    language: Language
    setLanguage: (lang: Language) => void
    t: (key: string) => string
}

const translations = {
    en: {
        // Navigation
        'nav.home': 'Home',
        'nav.artists': 'Artists',
        'nav.news': 'News',
        'nav.forum': 'Forum',
        'nav.login': 'Login',
        'nav.signup': 'Sign Up',

        // User Menu
        'user.profile': 'Profile',
        'user.settings': 'Settings',
        'user.logout': 'Logout',
        'user.anonymous': 'Anonymous',

        // Settings
        'settings.title': 'Settings',
        'settings.language': 'Language',
        'settings.language.desc': 'Select your preferred language for the interface.',
        'settings.personal_info': 'Personal Information',
        'settings.security': 'Security',
        'settings.change_password': 'Change Password',
        'settings.edit': 'Edit',
        'settings.cancel': 'Cancel',
        'settings.avatar.change': 'Change Avatar',
        'settings.avatar.uploading': 'Uploading...',
        'settings.avatar.success': 'Avatar uploaded successfully!',
        'settings.form.username': 'Username',
        'settings.form.email': 'Email',
        'settings.form.current_password': 'Current Password',
        'settings.form.new_password': 'New Password',
        'settings.form.confirm_password': 'Confirm Password',
        'settings.form.save': 'Save Changes',
        'settings.form.saving': 'Saving...',
        'settings.form.update_password': 'Update Password',
        'settings.profile.success': 'Profile updated successfully!',
        'settings.password.success': 'Password updated successfully!',
        'settings.error.password_mismatch': 'Passwords do not match',
        'settings.error.password_length': 'Password must be at least 6 characters',
        'settings.error.current_password_incorrect': 'Incorrect current password',
        'settings.error.file_size': 'File size must be less than 5MB',
        'settings.security.last_changed': 'Last Password Change',
        'settings.security.level': 'Security Level',
        'settings.security.weak': 'Weak',
        'settings.security.medium': 'Medium',
        'settings.security.strong': 'Strong',
        'settings.security.never': 'Never',
        'settings.appearance': 'Appearance',
        'settings.appearance.desc': 'Customize how MusicDisc looks on your device.',
        'settings.theme': 'Theme',
        'settings.theme.light': 'Light',
        'settings.theme.dark': 'Dark',
        'settings.theme.system': 'System',
        'settings.notifications': 'Notifications',
        'settings.notifications.desc': 'Manage your notification preferences.',
        'settings.notifications.email': 'Email Notifications',
        'settings.notifications.email.desc': 'Receive updates via email',
        'settings.notifications.push': 'Push Notifications',
        'settings.notifications.push.desc': 'Get browser notifications',
        'settings.notifications.forum': 'Forum Updates',
        'settings.notifications.forum.desc': 'Replies to your threads',
        'settings.privacy': 'Privacy',
        'settings.privacy.desc': 'Control your privacy and data settings.',
        'settings.privacy.profile': 'Public Profile',
        'settings.privacy.profile.desc': 'Make your profile visible to others',
        'settings.privacy.activity': 'Show Activity',
        'settings.privacy.activity.desc': 'Display your listening activity',
        'settings.account': 'Account Information',
        'settings.account.desc': 'Your account details and statistics.',
        'settings.account.created': 'Account Created',
        'settings.account.last_login': 'Last Login',
        'settings.account.posts': 'Forum Posts',
        'settings.account.comments': 'Comments',

        // Spotify
        'spotify.title': 'Spotify Integration',
        'spotify.desc': 'Connect your Spotify account to listen to music directly in the app.',
        'spotify.connected_as': 'Connected',
        'spotify.not_connected': 'Not Connected',
        'spotify.enjoy_music': 'You can now play music from the artist pages.',
        'spotify.connect_desc': 'Connect to unlock music playback.',
        'spotify.disconnect': 'Disconnect',
        'spotify.connect': 'Connect Spotify',

        // Common UI
        'common.loading': 'Loading...',
        'common.avatar': 'Avatar',
        'common.cancel': 'Cancel',
        'common.home': 'Home',
        'common.community': 'Community',
        'common.me': 'Me',
        'common.filters': 'Filters',

        // Errors
        'error.unknown': 'An unknown error occurred',
        'error.invalid_form': 'Invalid form data',
        'error.rate_limit.profile': 'Too many updates! Wait {seconds}s. (Limit: {max}/min)',
        'error.rate_limit.password': 'Too many password change attempts! Wait {minutes} minutes. (Limit: {max} per 5 minutes)',

        // Forum
        'forum.title': 'Community Forum',
        'forum.subtitle': 'Join the conversation, share your discoveries and connect with other music lovers.',
        'forum.search.placeholder': 'Search threads...',
        'forum.category.all': 'All Categories',
        'forum.sort.recent': 'Most Recent',
        'forum.sort.popular': 'Most Popular',
        'forum.sort.commented': 'Most Commented',
        'forum.pinned': 'Pinned',
        'forum.new_discussion': 'New Discussion',
        'forum.loading': 'Loading...',
        'forum.empty.title': 'No discussions yet',
        'forum.empty.message': 'Be the first to start a conversation',
        'forum.empty.message_category': 'in this category',
        'forum.login_required': 'You must log in to create a discussion',
        'forum.card.anonymous': 'Anonymous',
        'forum.card.pinned': 'Pinned',
        'forum.card.media_alt': 'Thread media',
        'forum.create.title': 'Title',
        'forum.create.title_placeholder': 'Write an interesting title...',
        'forum.create.category': 'Category',
        'forum.create.content': 'Content',
        'forum.create.content_placeholder': 'Share your thoughts...',
        'forum.create.multimedia': 'Multimedia (Optional)',
        'forum.create.upload_text': 'Click to upload image (max 5MB) or video (max 20MB)',
        'forum.create.preview': 'Preview',
        'forum.create.posting': 'Publishing...',
        'forum.create.publish': 'Publish',
        'forum.create.login_required': 'You must log in to post.',
        'forum.create.error.required': 'Title and content are required.',
        'forum.create.error.file_type': 'Only images or videos are allowed.',
        'forum.create.error.file_size': 'File is too large. Maximum {size}.',
        'forum.create.error.generic': 'Error creating thread.',
        'forum.thread.published': 'Published',
        'forum.thread.author': 'Thread Author',
        'forum.thread.back': 'Back to {category}',
        'forum.thread.back_community': 'Back to Community',
        'forum.thread.image_full': 'View full image',
        'forum.thread.image_attached': 'Attached image',
        'forum.thread.video_unsupported': 'Your browser does not support the video element.',
        'forum.thread.like': 'Like',
        'forum.thread.unlike': 'Unlike',
        'forum.thread.views': 'Views',
        'forum.thread.views_total': 'Total views',
        'forum.thread.login_to_like': 'Log in to like',
        'forum.thread.media_alt': 'Multimedia content',
        'forum.thread.media_fullscreen': 'Full screen multimedia content',
        'forum.comments.title': 'Comments',
        'forum.comments.write': 'Write Comment',
        'forum.comments.login_prompt': 'Log in to comment.',
        'forum.comments.reply': 'Reply',
        'forum.comments.reply_placeholder': 'Write your reply...',
        'forum.comments.share_opinion': 'Share your opinion...',
        'forum.comments.posting_as': 'Posting as',
        'forum.comments.posting': 'Publishing...',
        'forum.comments.publish': 'Publish Comment',
        'forum.comments.hide_replies': 'Hide replies',
        'forum.comments.view_replies': 'View {count} replies',
        'forum.comments.deleted_user': 'Deleted user',
        'forum.comments.login_to_like': 'Log in to like',
        'forum.sidebar.unknown': 'Unknown',


        // Auth
        'auth.login.title': 'Sign in to your account',
        'auth.login.subtitle': "Don't have an account?",
        'auth.login.cta': 'Sign up',
        'auth.login.button': 'Sign in',
        'auth.login.signing_in': 'Signing in...',
        'auth.signup.title': 'Create your account',
        'auth.signup.subtitle': 'Already have an account?',
        'auth.signup.cta': 'Sign in',
        'auth.signup.button': 'Create Account',
        'auth.signup.creating': 'Creating account...',
        'auth.form.email': 'Email address',
        'auth.form.password': 'Password',
        'auth.form.username': 'Username',
        'auth.form.confirm_password': 'Confirm Password',
        'auth.error.password_match': 'Passwords do not match',
        'auth.error.password_length': 'Password must be at least 6 characters',
        'auth.error.password_symbol': 'Password must contain at least one symbol',
        'auth.error.username_required': 'Username is required',
        'auth.error.username_length': 'Username must be at least 3 characters',
        'auth.error.email_required': 'Email is required',
        'auth.error.email_invalid': 'Please enter a valid email address',

        // News
        'news.title': 'Music News',
        'news.subtitle': 'Stay updated with the latest stories, reviews, and industry insights from the music world.',
        'news.loading': 'Loading news...',
        'news.empty': 'No news found in this category.',
        'news.views': 'views',
        'news.comments.title': 'Comments',
        'news.comments.placeholder': 'Leave a comment...',
        'news.comments.post': 'Post Comment',
        'news.comments.posting': 'Posting...',
        'news.comments.login_prompt': 'Please login to leave a comment.',
        'news.comments.empty': 'No comments yet. Be the first to comment!',

        // Artists
        'artists.title': 'Discover Artists',
        'artists.subtitle': 'Find your new favorite sound from our curated collection. Filter by genre or popularity.',
        'artists.search_placeholder': 'Search artists...',
        'artists.top_only': 'Top Artists Only',
        'artists.show_top': 'Show Top Artists',
        'artists.clear': 'Clear Filters',
        'artists.found': 'found',
        'artists.loading': 'Loading artists...',
        'artists.empty': 'No artists found',
        'artists.empty_desc': 'Try adjusting your search or filters',
        'artist.about': 'About',
        'artist.popular_songs': 'Popular Songs',
        'artist.discography': 'Discography',
        'artist.listeners': 'Monthly Listeners',
        'artist.top_songs': 'Top Songs',
        'artist.albums': 'Albums',
        'artist.total_plays': 'Total Plays',
        'artist.plays': 'plays',
        'artist.not_found': 'Artist not found',
        'artist.stats': 'Artist Stats',
        'artist.stats.genre': 'Genre',
        'artist.stats.followers': 'Followers',
        'artist.stats.songs': 'Songs',
        'artist.stats.albums': 'Albums',
        'artist.stats.total_plays': 'Total Plays',
        'artist.stats.genre_desc': 'Musical genre classification',
        'artist.stats.followers_desc': 'Total number of people following this artist',
        'artist.stats.songs_desc': 'Number of tracks in our database',
        'artist.stats.albums_desc': 'Number of albums released',
        'artist.stats.total_plays_desc': 'Combined plays across all songs',
        'artist.now_playing': 'Now Playing',
        'artist.back_to_results': 'Back to Results',
        'artist.returned_from': 'Returned from:',
        'artist.filter.genre': 'Genre:',
        'artist.filter.order': 'Order:',
        'artist.order.az': 'A-Z',
        'artist.order.newest': 'Newest',
        'artist.order.popular': 'Popular',
        'artist.all_genres': 'All Genres',
        'artists.sort.popular': 'Most Popular',
        'artists.sort.name': 'Name (A-Z)',
        'artists.sort.recent': 'Most Recent',
        'artists.load_more': 'Load More',
        'artists.loading_more': 'Loading...',

        // News detail
        'news.back_to_forum': 'Back to Forum',

        // Legal / Restricted
        'legal.restricted_title': 'Restricted Access',
        'legal.not_available_title': 'Content Not Available',
        'legal.privacy_restricted_msg': 'This section has been temporarily disabled due to updates in the legal compliance framework. Please try again later.',
        'legal.terms_restricted_msg': 'The Terms of Service are currently under technical and legal review. We apologize for the inconvenience, this section will be available soon.',
        'legal.back_home': 'Back to Home',

        // Home
        'home.hero.badge': 'Discover New Music',
        'home.hero.title': 'Discover Your Next Favorite Artist',
        'home.hero.subtitle': 'Explore a world of music, from chart-topping hits to underground gems.',
        'home.hero.cta': 'Start Listening',
        'home.scroll': 'Scroll to explore',
        'home.featured.title': 'Featured Artists',
        'home.featured.subtitle': 'Hand-picked artists making waves right now.',
        'home.news.title': 'Latest News',
        'home.news.subtitle': "What's happening in the music world.",
        'home.popularSongs.title': 'Popular Songs',
        'home.stats.artists': 'Artists',
        'home.stats.news': 'News Articles',
        'home.stats.updates': 'Updates',
        'home.features.title': 'Why Choose MusicDisc?',
        'home.features.discover.title': 'Discover',
        'home.features.discover.desc': 'Explore thousands of artists from every genre',
        'home.features.news.title': 'Stay Updated',
        'home.features.news.desc': 'Latest music news and releases daily',
        'home.features.listen.title': 'Listen',
        'home.features.listen.desc': 'Preview tracks directly from Spotify',
        'home.features.save.title': 'Save Favorites',
        'home.features.save.desc': 'Create your personal music collection',

        // Home Functions
        'home.functions.title': 'What you can do',
        'home.functions.subtitle': 'Unlock the full potential of MusicDisc',
        'home.function.search.title': 'Smart Search',
        'home.function.search.desc': 'Find artists, songs, and news instantly.',
        'home.function.forum.title': 'Community Forum',
        'home.function.forum.desc': 'Discuss topics, share playlists, and connect with fans.',
        'home.function.profile.title': 'User Profile',
        'home.function.profile.desc': 'Customize your avatar and track your activity.',
        'home.function.spotify.title': 'Spotify Integration',
        'home.function.spotify.desc': 'Connect your account to listen to full tracks.',

        // Footer
        'footer.description': 'Discover new artists, explore music news, and stay connected with the global music community.',
        'footer.platform': 'Platform',
        'footer.resources': 'Resources',
        'footer.legal': 'Legal',
        'footer.about': 'About',
        'footer.faq': 'FAQ',
        'footer.help': 'Help Center',
        'footer.api': 'API',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.cookies': 'Cookie Policy',
        'footer.rights': 'All rights reserved.',
        'footer.secure': 'Secure',
        'footer.trusted': 'Trusted',

        // Genres (no need to translate, they're universal)
        'genre.Pop': 'Pop',
        'genre.Rock': 'Rock',
        'genre.Indie': 'Indie',
        'genre.Hip Hop': 'Hip Hop',
        'genre.Rap': 'Rap',
        'genre.Electronic': 'Electronic',
        'genre.Jazz': 'Jazz',
        'genre.Classical': 'Classical',
        'genre.Metal': 'Metal',
        'genre.Country': 'Country',
        'genre.R&B': 'R&B',

        // Categories
        'category.Industry': 'Industry',
        'category.Reviews': 'Reviews',
        'category.Releases': 'Releases',
        'category.Live': 'Live',
    },
    es: {
        // Navigation
        'nav.home': 'Inicio',
        'nav.artists': 'Artistas',
        'nav.news': 'Noticias',
        'nav.forum': 'Foro',
        'nav.login': 'Iniciar Sesión',
        'nav.signup': 'Registrarse',

        // User Menu
        'user.profile': 'Perfil',
        'user.settings': 'Ajustes',
        'user.logout': 'Cerrar Sesión',
        'user.anonymous': 'Anónimo',

        // Settings
        'settings.title': 'Ajustes',
        'settings.language': 'Idioma',
        'settings.language.desc': 'Selecciona tu idioma preferido para la interfaz.',
        'settings.personal_info': 'Información Personal',
        'settings.security': 'Seguridad',
        'settings.change_password': 'Cambiar Contraseña',
        'settings.edit': 'Editar',
        'settings.cancel': 'Cancelar',
        'settings.avatar.change': 'Cambiar Avatar',
        'settings.avatar.uploading': 'Subiendo...',
        'settings.avatar.success': '¡Avatar subido con éxito!',
        'settings.form.username': 'Nombre de usuario',
        'settings.form.email': 'Correo electrónico',
        'settings.form.current_password': 'Contraseña Actual',
        'settings.form.new_password': 'Nueva Contraseña',
        'settings.form.confirm_password': 'Confirmar Contraseña',
        'settings.form.save': 'Guardar Cambios',
        'settings.form.saving': 'Guardando...',
        'settings.form.update_password': 'Actualizar Contraseña',
        'settings.profile.success': '¡Perfil actualizado con éxito!',
        'settings.password.success': '¡Contraseña actualizada con éxito!',
        'settings.error.password_mismatch': 'Las contraseñas no coinciden',
        'settings.error.password_length': 'La contraseña debe tener al menos 6 caracteres',
        'settings.error.current_password_incorrect': 'La contraseña actual es incorrecta',
        'settings.error.file_size': 'El archivo debe pesar menos de 5MB',
        'settings.security.last_changed': 'Último cambio de contraseña',
        'settings.security.level': 'Nivel de seguridad',
        'settings.security.weak': 'Débil',
        'settings.security.medium': 'Medio',
        'settings.security.strong': 'Fuerte',
        'settings.security.never': 'Nunca',
        'settings.appearance': 'Apariencia',
        'settings.appearance.desc': 'Personaliza cómo se ve MusicDisc en tu dispositivo.',
        'settings.theme': 'Tema',
        'settings.theme.light': 'Claro',
        'settings.theme.dark': 'Oscuro',
        'settings.theme.system': 'Sistema',
        'settings.notifications': 'Notificaciones',
        'settings.notifications.desc': 'Administra tus preferencias de notificaciones.',
        'settings.notifications.email': 'Notificaciones por Email',
        'settings.notifications.email.desc': 'Recibir actualizaciones por correo',
        'settings.notifications.push': 'Notificaciones Push',
        'settings.notifications.push.desc': 'Recibir notificaciones del navegador',
        'settings.notifications.forum': 'Actualizaciones del Foro',
        'settings.notifications.forum.desc': 'Respuestas a tus discusiones',
        'settings.privacy': 'Privacidad',
        'settings.privacy.desc': 'Controla tu privacidad y configuración de datos.',
        'settings.privacy.profile': 'Perfil Público',
        'settings.privacy.profile.desc': 'Hacer tu perfil visible para otros',
        'settings.privacy.activity': 'Mostrar Actividad',
        'settings.privacy.activity.desc': 'Mostrar tu actividad de escucha',
        'settings.account': 'Información de Cuenta',
        'settings.account.desc': 'Detalles y estadísticas de tu cuenta.',
        'settings.account.created': 'Cuenta Creada',
        'settings.account.last_login': 'Último Inicio de Sesión',
        'settings.account.posts': 'Publicaciones en Foro',
        'settings.account.comments': 'Comentarios',

        // Spotify
        'spotify.title': 'Integración con Spotify',
        'spotify.desc': 'Conecta tu cuenta de Spotify para escuchar música directamente en la aplicación.',
        'spotify.connected_as': 'Conectado',
        'spotify.not_connected': 'No Conectado',
        'spotify.enjoy_music': 'Ahora puedes reproducir música desde las páginas de los artistas.',
        'spotify.connect_desc': 'Conéctate para desbloquear la reproducción de música.',
        'spotify.disconnect': 'Desconectar',
        'spotify.connect': 'Conectar Spotify',

        // Common UI
        'common.loading': 'Cargando...',
        'common.avatar': 'Avatar',
        'common.cancel': 'Cancelar',
        'common.home': 'Inicio',
        'common.community': 'Comunidad',
        'common.me': 'Yo',
        'common.filters': 'Filtros',

        // Errors
        'error.unknown': 'Ocurrió un error desconocido',
        'error.invalid_form': 'Datos del formulario inválidos',
        'error.rate_limit.profile': '¡Demasiadas actualizaciones! Espera {seconds}s. (Límite: {max}/min)',
        'error.rate_limit.password': '¡Demasiados intentos de cambio de contraseña! Espera {minutes} minutos. (Límite: {max} cada 5 minutos)',

        // Forum
        'forum.title': 'Foro de la Comunidad',
        'forum.subtitle': 'Únete a la conversación, comparte tus descubrimientos y conecta con otros amantes de la música.',
        'forum.search.placeholder': 'Buscar threads...',
        'forum.category.all': 'Todas las Categorías',
        'forum.sort.recent': 'Más Reciente',
        'forum.sort.popular': 'Más Popular',
        'forum.sort.commented': 'Más Comentados',
        'forum.pinned': 'Anclados',
        'forum.new_discussion': 'Nueva Discusión',
        'forum.loading': 'Cargando...',
        'forum.empty.title': 'No hay discusiones todavía',
        'forum.empty.message': 'Sé el primero en iniciar una conversación',
        'forum.empty.message_category': 'en esta categoría',
        'forum.login_required': 'Debes iniciar sesión para crear una discusión',
        'forum.card.anonymous': 'Anónimo',
        'forum.card.pinned': 'Anclado',
        'forum.card.media_alt': 'Multimedia del tema',
        'forum.create.title': 'Título',
        'forum.create.title_placeholder': 'Escribe un título interesante...',
        'forum.create.category': 'Categoría',
        'forum.create.content': 'Contenido',
        'forum.create.content_placeholder': 'Comparte tus pensamientos...',
        'forum.create.multimedia': 'Multimedia (Opcional)',
        'forum.create.upload_text': 'Haz clic para subir imagen (max 5MB) o video (max 20MB)',
        'forum.create.preview': 'Vista previa',
        'forum.create.posting': 'Publicando...',
        'forum.create.publish': 'Publicar',
        'forum.create.login_required': 'Debes iniciar sesión para publicar.',
        'forum.create.error.required': 'Título y contenido son obligatorios.',
        'forum.create.error.file_type': 'Solo se permiten imágenes o videos.',
        'forum.create.error.file_size': 'El archivo es demasiado grande. Máximo {size}.',
        'forum.create.error.generic': 'Error al crear el hilo.',
        'forum.thread.published': 'Publicado',
        'forum.thread.author': 'Autor del Hilo',
        'forum.thread.back': 'Volver a {category}',
        'forum.thread.back_community': 'Volver a la Comunidad',
        'forum.thread.image_full': 'Ver imagen completa',
        'forum.thread.image_attached': 'Imagen adjunta',
        'forum.thread.video_unsupported': 'Tu navegador no soporta el elemento de video.',
        'forum.thread.like': 'Me gusta',
        'forum.thread.unlike': 'Ya no me gusta',
        'forum.thread.views': 'Vistas',
        'forum.thread.views_total': 'Vistas totales',
        'forum.thread.login_to_like': 'Inicia sesión para dar like',
        'forum.thread.media_alt': 'Contenido multimedia',
        'forum.thread.media_fullscreen': 'Contenido multimedia pantalla completa',
        'forum.comments.title': 'Comentarios',
        'forum.comments.write': 'Escribir Comentario',
        'forum.comments.login_prompt': 'Inicia sesión para comentar.',
        'forum.comments.reply': 'Responder',
        'forum.comments.reply_placeholder': 'Escribe tu respuesta...',
        'forum.comments.share_opinion': 'Comparte tu opinión...',
        'forum.comments.posting_as': 'Publicando como',
        'forum.comments.posting': 'Publicando...',
        'forum.comments.publish': 'Publicar Comentario',
        'forum.comments.hide_replies': 'Ocultar respuestas',
        'forum.comments.view_replies': 'Ver {count} respuestas',
        'forum.comments.deleted_user': 'Usuario eliminado',
        'forum.comments.login_to_like': 'Inicia sesión para dar like',
        'forum.sidebar.unknown': 'Desconocido',

        // Auth
        'auth.login.title': 'Inicia sesión en tu cuenta',
        'auth.login.subtitle': '¿No tienes una cuenta?',
        'auth.login.cta': 'Regístrate',
        'auth.login.button': 'Iniciar sesión',
        'auth.login.signing_in': 'Iniciando sesión...',
        'auth.signup.title': 'Crea tu cuenta',
        'auth.signup.subtitle': '¿Ya tienes una cuenta?',
        'auth.signup.cta': 'Inicia sesión',
        'auth.signup.button': 'Crear Cuenta',
        'auth.signup.creating': 'Creando cuenta...',
        'auth.form.email': 'Correo electrónico',
        'auth.form.password': 'Contraseña',
        'auth.form.username': 'Nombre de usuario',
        'auth.form.confirm_password': 'Confirmar Contraseña',
        'auth.error.password_match': 'Las contraseñas no coinciden',
        'auth.error.password_length': 'La contraseña debe tener al menos 6 caracteres',
        'auth.error.password_symbol': 'La contraseña debe contener al menos un símbolo',
        'auth.error.username_required': 'El nombre de usuario es obligatorio',
        'auth.error.username_length': 'El nombre de usuario debe tener al menos 3 caracteres',
        'auth.error.email_required': 'El correo electrónico es obligatorio',
        'auth.error.email_invalid': 'Por favor introduce un correo válido',

        // News
        'news.title': 'Noticias Musicales',
        'news.subtitle': 'Mantente actualizado con las últimas historias, reseñas y noticias de la industria musical.',
        'news.loading': 'Cargando noticias...',
        'news.empty': 'No se encontraron noticias en esta categoría.',
        'news.views': 'vistas',
        'news.comments.title': 'Comentarios',
        'news.comments.placeholder': 'Deja un comentario...',
        'news.comments.post': 'Publicar Comentario',
        'news.comments.posting': 'Publicando...',
        'news.comments.login_prompt': 'Por favor inicia sesión para dejar un comentario.',
        'news.comments.empty': 'Aún no hay comentarios. ¡Sé el primero en comentar!',

        // Artists
        'artists.title': 'Descubrir Artistas',
        'artists.subtitle': 'Encuentra tu nuevo sonido favorito en nuestra colección curada. Filtra por género o popularidad.',
        'artists.search_placeholder': 'Buscar artistas...',
        'artists.top_only': 'Solo Top Artistas',
        'artists.show_top': 'Mostrar Top Artistas',
        'artists.clear': 'Limpiar Filtros',
        'artists.found': 'encontrados',
        'artists.loading': 'Cargando artistas...',
        'artists.empty': 'No se encontraron artistas',
        'artists.empty_desc': 'Intenta ajustar tu búsqueda o filtros',
        'artist.about': 'Acerca de',
        'artist.popular_songs': 'Canciones Populares',
        'artist.discography': 'Discografía',
        'artist.listeners': 'Oyentes Mensuales',
        'artist.top_songs': 'Top Canciones',
        'artist.albums': 'Álbumes',
        'artist.total_plays': 'Reproducciones Totales',
        'artist.plays': 'reproducciones',
        'artist.not_found': 'Artista no encontrado',
        'artist.stats': 'Estadísticas del Artista',
        'artist.stats.genre': 'Género',
        'artist.stats.followers': 'Seguidores',
        'artist.stats.songs': 'Canciones',
        'artist.stats.albums': 'Álbumes',
        'artist.stats.total_plays': 'Reproducciones',
        'artist.stats.genre_desc': 'Clasificación del género musical',
        'artist.stats.followers_desc': 'Número total de personas siguiendo a este artista',
        'artist.stats.songs_desc': 'Número de pistas en nuestra base de datos',
        'artist.stats.albums_desc': 'Número de álbumes lanzados',
        'artist.stats.total_plays_desc': 'Reproducciones combinadas de todas las canciones',
        'artist.now_playing': 'Reproduciendo Ahora',
        'artist.back_to_results': 'Volver a resultados',
        'artist.returned_from': 'Volviste de:',
        'artist.filter.genre': 'Género:',
        'artist.filter.order': 'Orden:',
        'artist.order.az': 'A-Z',
        'artist.order.newest': 'Reciente',
        'artist.order.popular': 'Popular',
        'artist.all_genres': 'Todos los Géneros',
        'artists.sort.popular': 'Más Popular',
        'artists.sort.name': 'Nombre (A-Z)',
        'artists.sort.recent': 'Más Reciente',
        'artists.load_more': 'Cargar Más',
        'artists.loading_more': 'Cargando...',

        // News detail
        'news.back_to_forum': 'Volver al Foro',

        // Legal / Restricted
        'legal.restricted_title': 'Acceso Restringido',
        'legal.not_available_title': 'Contenido No Disponible',
        'legal.privacy_restricted_msg': 'Esta sección ha sido deshabilitada temporalmente por actualizaciones en el marco de cumplimiento legal. Por favor, vuelve a intentarlo más tarde.',
        'legal.terms_restricted_msg': 'Los Términos de Servicio se encuentran en revisión técnica y legal. Lamentamos los inconvenientes, esta sección estará disponible próximamente.',
        'legal.back_home': 'Volver al Inicio',

        // Home
        'home.hero.badge': 'Descubre Nueva Música',
        'home.hero.title': 'Descubre tu Próximo Artista Favorito',
        'home.hero.subtitle': 'Explora un mundo de música, desde éxitos de las listas hasta joyas underground.',
        'home.hero.cta': 'Empezar a Escuchar',
        'home.scroll': 'Desplázate para explorar',
        'home.featured.title': 'Artistas Destacados',
        'home.featured.subtitle': 'Artistas seleccionados que están marcando tendencia ahora mismo.',
        'home.news.title': 'Últimas Noticias',
        'home.news.subtitle': 'Lo que está pasando en el mundo de la música.',
        'home.popularSongs.title': 'Canciones Populares',
        'home.stats.artists': 'Artistas',
        'home.stats.news': 'Artículos',
        'home.stats.updates': 'Actualizaciones',
        'home.features.title': '¿Por qué elegir MusicDisc?',
        'home.features.discover.title': 'Descubre',
        'home.features.discover.desc': 'Explora artistas de todos los géneros',
        'home.features.news.title': 'Mantente Actualizado',
        'home.features.news.desc': 'Últimas noticias musicales y lanzamientos diarios',
        'home.features.listen.title': 'Escucha',
        'home.features.listen.desc': 'Previsualiza canciones directamente desde Spotify',
        'home.features.save.title': 'Guarda Favoritos',
        'home.features.save.desc': 'Crea tu colección personal de música',

        // Home Functions
        'home.functions.title': 'Lo que puedes hacer',
        'home.functions.subtitle': 'Desbloquea todo el potencial de MusicDisc',
        'home.function.search.title': 'Búsqueda Inteligente',
        'home.function.search.desc': 'Encuentra artistas, canciones y noticias al instante.',
        'home.function.forum.title': 'Foro de la Comunidad',
        'home.function.forum.desc': 'Discute temas, comparte playlists y conecta con fans.',
        'home.function.profile.title': 'Perfil de Usuario',
        'home.function.profile.desc': 'Personaliza tu avatar y sigue tu actividad.',
        'home.function.spotify.title': 'Integración Spotify',
        'home.function.spotify.desc': 'Conecta tu cuenta para escuchar canciones completas.',

        // Footer
        'footer.description': 'Descubre nuevos artistas, explora noticias musicales y mantente conectado con la comunidad musical global.',
        'footer.platform': 'Plataforma',
        'footer.resources': 'Recursos',
        'footer.legal': 'Legal',
        'footer.about': 'Acerca de',
        'footer.faq': 'Preguntas Frecuentes',
        'footer.help': 'Centro de Ayuda',
        'footer.api': 'API',
        'footer.privacy': 'Política de Privacidad',
        'footer.terms': 'Términos de Servicio',
        'footer.cookies': 'Política de Cookies',
        'footer.rights': 'Todos los derechos reservados.',
        'footer.secure': 'Seguro',
        'footer.trusted': 'Confiable',

        // Genres
        'genre.Pop': 'Pop',
        'genre.Rock': 'Rock',
        'genre.Indie': 'Indie',
        'genre.Hip Hop': 'Hip Hop',
        'genre.Rap': 'Rap',
        'genre.Electronic': 'Electrónica',
        'genre.Jazz': 'Jazz',
        'genre.Classical': 'Clásica',
        'genre.Metal': 'Metal',
        'genre.Country': 'Country',
        'genre.R&B': 'R&B',

        // Categories
        'category.Industry': 'Industria',
        'category.Reviews': 'Reseñas',
        'category.Releases': 'Lanzamientos',
        'category.Live': 'En Vivo',
    },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('es')

    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language
        if (savedLang && Object.keys(translations).includes(savedLang)) {
            setLanguageState(savedLang)
        }
    }, [])

    const setLanguage = (lang: Language) => {
        setLanguageState(lang)
        localStorage.setItem('language', lang)
    }

    const t = (key: string): string => {
        const langData = translations[language] as Record<string, string>
        return langData[key] || key
    }

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    )
}

export function useLanguage() {
    const context = useContext(LanguageContext)
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider')
    }
    return context
}
